version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          # No published source tarball for 0.74.3
          dependency_name: "simple-salesforce"
          version_requirement: "0.74.2"
    